// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vhbxteiciqieitdpjpmo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZoYnh0ZWljaXFpZWl0ZHBqcG1vIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQyMTMwOTksImV4cCI6MjA2OTc4OTA5OX0.mGAdsgItP1kG_OlhuMQOKIPjZn_oaSXGmUH83FfFaUc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});